#!/usr/bin/env bash
# 5-dont_stop_me_now
# This script traps SIGTERM and displays a message before stopping

trap "echo 'Oh no, they killed me 😭'" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
